stages:
  train:
    cmd: python -m src.main
    deps:
    - src/
    params:
    - params.yml:
    outs:
    - logdir/
    metrics:
    - summary/metrics.json:
        cache: false
  postprocess:
    cmd: postproc.py
    deps:
    - logdir/
    plots:
    - summary/mse_loss:
        cache: false
