stages:
  train:
    cmd: python -m src.main
    deps:
    - src/
    params:
    - params.yml
    outs:
    - logdir/state.pt      
    metrics:
            - logdir/metric.json:
                    cache: False
