vars:
  - run: 3

stages:
  train:
    cmd: python -m src.main ${run}
    deps:
    - src/
    params:
    - params.yml:
    outs:
    - logdir/
    metrics:
    - summary/metrics.json:
        cache: false

  postprocess:
    cmd: python postproc.py
    deps:
    - logdir/
    plots:
    - summary/mse_loss:
        cache: false

  push_to_yc:
    cmd: python push_to_yc.py ${run}
    deps:
    - push_to_yc.py